/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import civitas.Casilla;
import civitas.CasillaCalle;
import java.awt.Color;

/**
 *
 * @author Usuario
 */
public class CasillaPanel extends javax.swing.JPanel {

    /**
     * Creates new form CasillaPanel
     */
    
    private Casilla casillaPasillo;
    
    public CasillaPanel() {
        casillaPasillo = null;
        initComponents();
    }
    
    public void setCasillaPasillo(Casilla casillaPasillo, boolean actual){
        
        this.casillaPasillo = casillaPasillo;
        casilla_pasillo_text_field.setText(casillaPasillo.getNombre());
        
        if (casillaPasillo instanceof CasillaCalle) {
            CasillaCalle c =(CasillaCalle)casillaPasillo;
            precio_text_field.setText(String.valueOf(c.getPrecioCompra())+ "€");
        }
        else
        {
            precio_text_field.setVisible(false);
        }
        
        if(actual){
            this.setBackground(Color.cyan);
        }
        repaint();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        casilla_pasillo_text_field = new javax.swing.JTextField();
        precio_text_field = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        setMaximumSize(new java.awt.Dimension(100, 80));
        setMinimumSize(new java.awt.Dimension(100, 80));
        setPreferredSize(new java.awt.Dimension(100, 80));

        casilla_pasillo_text_field.setEditable(false);
        casilla_pasillo_text_field.setBackground(new java.awt.Color(255, 255, 255));
        casilla_pasillo_text_field.setFont(new java.awt.Font("Script MT Bold", 0, 10)); // NOI18N
        casilla_pasillo_text_field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        casilla_pasillo_text_field.setText("Casilla");
        casilla_pasillo_text_field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        casilla_pasillo_text_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla_pasillo_text_fieldActionPerformed(evt);
            }
        });

        precio_text_field.setEditable(false);
        precio_text_field.setBackground(new java.awt.Color(255, 255, 204));
        precio_text_field.setFont(new java.awt.Font("Ravie", 0, 6)); // NOI18N
        precio_text_field.setText("precio");
        precio_text_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precio_text_fieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(casilla_pasillo_text_field, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(precio_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(casilla_pasillo_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(precio_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void casilla_pasillo_text_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla_pasillo_text_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casilla_pasillo_text_fieldActionPerformed

    private void precio_text_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precio_text_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precio_text_fieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField casilla_pasillo_text_field;
    private javax.swing.JTextField precio_text_field;
    // End of variables declaration//GEN-END:variables
}
