/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import civitas.CivitasJuego;
import civitas.Jugador;
import civitas.OperacionInmobiliaria;
import civitas.OperacionJuego;
import controladorCivitas.Respuesta;
import java.util.ArrayList;
import javax.swing.*;  
import civitas.Diario;



/**
 *
 * @author Usuario
 */
public class CivitasView extends javax.swing.JFrame implements Vista{

    /**
     * Creates new form CivitasView
     */ 
    private CivitasJuego juego; 
    private DiarioDialog diarioD; 
    
    public CivitasView() {
        juego = null;
        diarioD = null;
        initComponents();   
    }
    
    public void setCivitasJuego(CivitasJuego juego){
        
        this.juego = juego;
        panelTablero3.setTablero(juego);
        setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTablero2 = new GUI.PanelTablero();
        titulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        siguiente_op_label = new javax.swing.JLabel();
        siguiente_op_text_field = new javax.swing.JTextField();
        ranking_label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ranking_text_area = new javax.swing.JTextArea();
        panelTablero3 = new GUI.PanelTablero();
        jugadorPanel1 = new GUI.JugadorPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Ravie", 2, 24)); // NOI18N
        titulo.setText("Juego: Civitas");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        siguiente_op_label.setFont(new java.awt.Font("Ravie", 2, 14)); // NOI18N
        siguiente_op_label.setText("Siguiente Operación:");

        siguiente_op_text_field.setEditable(false);
        siguiente_op_text_field.setBackground(new java.awt.Color(204, 204, 204));
        siguiente_op_text_field.setFont(new java.awt.Font("Ravie", 2, 18)); // NOI18N
        siguiente_op_text_field.setForeground(new java.awt.Color(255, 0, 0));
        siguiente_op_text_field.setText("Siguiente Operacion");
        siguiente_op_text_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguiente_op_text_fieldActionPerformed(evt);
            }
        });

        ranking_label.setFont(new java.awt.Font("Ravie", 2, 14)); // NOI18N
        ranking_label.setText("Ranking:");

        ranking_text_area.setBackground(new java.awt.Color(255, 255, 204));
        ranking_text_area.setColumns(20);
        ranking_text_area.setFont(new java.awt.Font("Ravie", 0, 12)); // NOI18N
        ranking_text_area.setForeground(new java.awt.Color(0, 0, 0));
        ranking_text_area.setRows(5);
        jScrollPane1.setViewportView(ranking_text_area);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(siguiente_op_label)
                            .addComponent(ranking_label, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(siguiente_op_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(siguiente_op_label)
                .addGap(18, 18, 18)
                .addComponent(siguiente_op_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(ranking_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jugadorPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(panelTablero3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jugadorPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(panelTablero3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void siguiente_op_text_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguiente_op_text_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_siguiente_op_text_fieldActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CivitasView().setVisible(true);
            }
        });
        */
    }
    
        
    @Override    
    public void actualiza(){
        
        jugadorPanel1.setJugador(juego.getJugadorActual());
        panelTablero3.setTablero(juego);
        //ranking_label.setVisible(false);
        ranking_text_area.setVisible(false);
        
        if(juego.finalDelJuego()){
            
            ranking_label.setVisible(true);
            
            ArrayList<Jugador> jugadores = juego._ranking();
            String cadena = "";
            
            for(int n=0; n<jugadores.size(); n++){
                cadena += n + ". " + jugadores.get(n).getNombre()+ "\n";
            }
                
            ranking_text_area.setText(cadena);
            ranking_text_area.setVisible(true);
            
            repaint();
            revalidate();
           
        }
    }

    @Override
    public void pausa(){
        int val= JOptionPane.showConfirmDialog(null, "¿Continuar?", "Siguiente paso", JOptionPane.YES_NO_OPTION);   
        if (val==1) System.exit(0);
    }

    @Override
    public Respuesta comprar(){
        
        int opcion = 1-JOptionPane.showConfirmDialog(null, "¿Quieres comprar la calle actual?", "Compra", JOptionPane.YES_NO_OPTION);
        
        if(opcion == 0){
            return Respuesta.NO;
        }
        else {
            return Respuesta.SI;
        }
        
    }
    
    @Override
    public OperacionInmobiliaria elegirOperacion(){
        
        GestionarDialog gestion = new GestionarDialog(this, true);
        int opcion = gestion.getGestion();
        
        if(opcion == 0){
            return OperacionInmobiliaria.CONSTRUIR_CASA;
        }
        else if(opcion == 1){
            return OperacionInmobiliaria.CONSTRUIR_HOTEL;
        }
        else {
            return OperacionInmobiliaria.TERMINAR;
        }
    }

    @Override
    public int elegirPropiedad(){
    
        PropiedadDialog elegir_propiedad = new PropiedadDialog(this, true, juego.getJugadorActual());
        int opcion = elegir_propiedad.getPropiedadElegida();
        return opcion;
    }

    @Override
    public void mostrarSiguienteOperacion(OperacionJuego operacion){
        siguiente_op_text_field.setText(operacion.name());
        
        if(operacion == OperacionJuego.AVANZAR){
            vistaDado.createInstance(this);
            vistaDado.getInstance().setVisible(true);
            
        }
        
        repaint();
    }

    @Override
    public void mostrarEventos(){
    
         if (!Diario.getInstance().getEventos().isEmpty())
             diarioD = new DiarioDialog(this, true);
            
    }
    
    public void mostrarEstado(){}
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private GUI.JugadorPanel jugadorPanel1;
    private GUI.PanelTablero panelTablero2;
    private GUI.PanelTablero panelTablero3;
    private javax.swing.JLabel ranking_label;
    private javax.swing.JTextArea ranking_text_area;
    private javax.swing.JLabel siguiente_op_label;
    private javax.swing.JTextField siguiente_op_text_field;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
