/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import civitas.Jugador;
import java.util.ArrayList;
import civitas.CasillaCalle;

/**
 *
 * @author Usuario
 */
public class JugadorPanel extends javax.swing.JPanel {

    /**
     * Creates new form JugadorPanel
     */
    private Jugador jugador;
    
    public JugadorPanel() {
        jugador = null;
        initComponents();
    }
        
    public void setJugador(Jugador jugador){
        
        this.jugador = jugador;
        nombre_text_field.setText(jugador.getNombre());
        saldo_text_field.setText(String.valueOf(jugador.getSaldo()));
        especulador_text_field.setText(String.valueOf(jugador.esEspeculador()));
        rellenaPropiedades(jugador.getPropiedades());
        
        repaint();
        revalidate();
    }
    
    public void rellenaPropiedades(ArrayList<CasillaCalle> lista){
        
        // Se elimina la información antigua
        propiedadesPanel.removeAll();
        // Se recorre la lista de propiedades para ir creando sus vistas
        // individuales y añadirlas al panel
        for (CasillaCalle t : lista) {
        PropiedadPanel vistaPropiedad = new PropiedadPanel();
        vistaPropiedad.setPropiedad(t);

        propiedadesPanel.add(vistaPropiedad);
        vistaPropiedad.setVisible(true);
        }
        // Se fuerza la actualización visual del panel propiedades y del
       // panel del jugador
        repaint();
        revalidate();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre_label = new javax.swing.JLabel();
        nombre_text_field = new javax.swing.JTextField();
        saldo_label = new javax.swing.JLabel();
        saldo_text_field = new javax.swing.JTextField();
        especulador_label = new javax.swing.JLabel();
        especulador_text_field = new javax.swing.JTextField();
        propiedadesPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nombre_label.setFont(new java.awt.Font("Ravie", 2, 14)); // NOI18N
        nombre_label.setText("Nombre:");

        nombre_text_field.setEditable(false);
        nombre_text_field.setBackground(new java.awt.Color(204, 204, 204));
        nombre_text_field.setFont(new java.awt.Font("Ravie", 2, 14)); // NOI18N
        nombre_text_field.setForeground(new java.awt.Color(255, 255, 0));
        nombre_text_field.setText("Nombre");
        nombre_text_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_text_fieldActionPerformed(evt);
            }
        });

        saldo_label.setFont(new java.awt.Font("Ravie", 2, 14)); // NOI18N
        saldo_label.setText("Saldo:");

        saldo_text_field.setEditable(false);
        saldo_text_field.setBackground(new java.awt.Color(204, 204, 204));
        saldo_text_field.setFont(new java.awt.Font("Ravie", 2, 14)); // NOI18N
        saldo_text_field.setForeground(new java.awt.Color(255, 255, 0));
        saldo_text_field.setText("Saldo");

        especulador_label.setFont(new java.awt.Font("Ravie", 2, 14)); // NOI18N
        especulador_label.setText("Especulador:");

        especulador_text_field.setEditable(false);
        especulador_text_field.setBackground(new java.awt.Color(204, 204, 204));
        especulador_text_field.setFont(new java.awt.Font("Ravie", 2, 14)); // NOI18N
        especulador_text_field.setForeground(new java.awt.Color(255, 255, 0));
        especulador_text_field.setText("Especulador");

        propiedadesPanel.setBackground(new java.awt.Color(207, 170, 115));
        propiedadesPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        propiedadesPanel.setAutoscrolls(true);

        jLabel1.setFont(new java.awt.Font("Ravie", 2, 14)); // NOI18N
        jLabel1.setText("Lista de Propiedades del Jugador:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nombre_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombre_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saldo_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saldo_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(especulador_label)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(especulador_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(propiedadesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre_label)
                    .addComponent(saldo_label)
                    .addComponent(saldo_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(especulador_label)
                    .addComponent(especulador_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(propiedadesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nombre_text_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_text_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_text_fieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel especulador_label;
    private javax.swing.JTextField especulador_text_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nombre_label;
    private javax.swing.JTextField nombre_text_field;
    private javax.swing.JPanel propiedadesPanel;
    private javax.swing.JLabel saldo_label;
    private javax.swing.JTextField saldo_text_field;
    // End of variables declaration//GEN-END:variables
}
