/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import civitas.CasillaCalle;

/**
 *
 * @author Usuario
 */
public class PropiedadPanel extends javax.swing.JPanel {

    /**
     * Creates new form PropiedadPanel
     */
    
    private CasillaCalle tituloPropiedad;
    
    public PropiedadPanel() {
        tituloPropiedad = null;
        initComponents();
    }
    
    public void setPropiedad(CasillaCalle tituloPropiedad){
        
        this.tituloPropiedad = tituloPropiedad;
        nombre_casilla_text_field.setText(tituloPropiedad.getNombre());
        num_casas_text_field.setText(String.valueOf(tituloPropiedad.getNumCasas()));
        num_hoteles_text_field.setText(String.valueOf(tituloPropiedad.getNumHoteles()));
        
        precio_edificar.setText(String.valueOf(tituloPropiedad.getPrecioEdificar()));
        repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        num_casas_label = new javax.swing.JLabel();
        num_hoteles_label = new javax.swing.JLabel();
        nombre_casilla_text_field = new javax.swing.JTextField();
        num_casas_text_field = new javax.swing.JTextField();
        num_hoteles_text_field = new javax.swing.JTextField();
        precio_edificar = new javax.swing.JTextField();
        num_hoteles_label1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        num_casas_label.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        num_casas_label.setText("Numero de Casas:");

        num_hoteles_label.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        num_hoteles_label.setText("Numero de Hoteles:");

        nombre_casilla_text_field.setEditable(false);
        nombre_casilla_text_field.setBackground(new java.awt.Color(204, 204, 255));
        nombre_casilla_text_field.setFont(new java.awt.Font("Ravie", 0, 8)); // NOI18N
        nombre_casilla_text_field.setText("Nombre Casilla");
        nombre_casilla_text_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_casilla_text_fieldActionPerformed(evt);
            }
        });

        num_casas_text_field.setEditable(false);
        num_casas_text_field.setBackground(new java.awt.Color(255, 255, 255));
        num_casas_text_field.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        num_casas_text_field.setText("Numero de Casas");
        num_casas_text_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_casas_text_fieldActionPerformed(evt);
            }
        });

        num_hoteles_text_field.setEditable(false);
        num_hoteles_text_field.setBackground(new java.awt.Color(255, 255, 255));
        num_hoteles_text_field.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        num_hoteles_text_field.setText("Numero de Hoteles");

        precio_edificar.setEditable(false);
        precio_edificar.setBackground(new java.awt.Color(255, 255, 255));
        precio_edificar.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        precio_edificar.setText("Numero de Casas");
        precio_edificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precio_edificarActionPerformed(evt);
            }
        });

        num_hoteles_label1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        num_hoteles_label1.setText("Precio Edificar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nombre_casilla_text_field, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(num_casas_label, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(num_hoteles_label, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(num_casas_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num_hoteles_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(num_hoteles_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(precio_edificar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombre_casilla_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num_casas_label, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num_casas_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num_hoteles_label, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num_hoteles_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num_hoteles_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precio_edificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nombre_casilla_text_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_casilla_text_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_casilla_text_fieldActionPerformed

    private void num_casas_text_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_casas_text_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_casas_text_fieldActionPerformed

    private void precio_edificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precio_edificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precio_edificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField nombre_casilla_text_field;
    private javax.swing.JLabel num_casas_label;
    private javax.swing.JTextField num_casas_text_field;
    private javax.swing.JLabel num_hoteles_label;
    private javax.swing.JLabel num_hoteles_label1;
    private javax.swing.JTextField num_hoteles_text_field;
    private javax.swing.JTextField precio_edificar;
    // End of variables declaration//GEN-END:variables
}
