/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "calculadora.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

calc_res *
sumar_1(Operacion arg1,  CLIENT *clnt)
{
	static calc_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SUMAR,
		(xdrproc_t) xdr_Operacion, (caddr_t) &arg1,
		(xdrproc_t) xdr_calc_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

calc_res *
restar_1(Operacion arg1,  CLIENT *clnt)
{
	static calc_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RESTAR,
		(xdrproc_t) xdr_Operacion, (caddr_t) &arg1,
		(xdrproc_t) xdr_calc_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

calc_res *
multiplicar_1(Operacion arg1,  CLIENT *clnt)
{
	static calc_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, MULTIPLICAR,
		(xdrproc_t) xdr_Operacion, (caddr_t) &arg1,
		(xdrproc_t) xdr_calc_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

calc_res *
dividir_1(Operacion arg1,  CLIENT *clnt)
{
	static calc_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, DIVIDIR,
		(xdrproc_t) xdr_Operacion, (caddr_t) &arg1,
		(xdrproc_t) xdr_calc_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

calc_res_vec *
op_compleja_server_1(vOper arg1,  CLIENT *clnt)
{
	static calc_res_vec clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, OP_COMPLEJA_SERVER,
		(xdrproc_t) xdr_vOper, (caddr_t) &arg1,
		(xdrproc_t) xdr_calc_res_vec, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

calc_res_vec *
op_vectores_server_1(resVec arg1, resVec arg2, int arg3,  CLIENT *clnt)
{
	op_vectores_server_1_argument arg;
	static calc_res_vec clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	if (clnt_call (clnt, OP_VECTORES_SERVER, (xdrproc_t) xdr_op_vectores_server_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_calc_res_vec, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
