/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package practica2;

import java.awt.Graphics;
import java.awt.Color;

public class MapaPanel extends javax.swing.JPanel {

    private Mapa mapa;
    private int agenteX, agenteY;
    private final int CELL_SIZE = 20; // Mantener la misma constante de tamaño de celda

    public MapaPanel(Mapa mapa, int agenteX, int agenteY) {
        this.mapa = mapa;
        this.agenteX = agenteX;
        this.agenteY = agenteY;
        initComponents();
    }

    public void setAgentePosicion(int x, int y) {
        this.agenteX = x;
        this.agenteY = y;
        repaint(); // Repintar el mapa cada vez que el agente cambia de posición
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        for (int i = 0; i < mapa.getFilas(); i++) {
            for (int j = 0; j < mapa.getColumnas(); j++) {
                if (i == agenteX && j == agenteY) {
                    g.setColor(Color.BLUE);
                } else if (mapa.isObstacle(i, j)) {
                    g.setColor(Color.BLACK);
                } else if (mapa.isObjetivo(i, j)) {
                    g.setColor(Color.RED);
                } else {
                    g.setColor(Color.WHITE);
                }
                g.fillRect(j * CELL_SIZE, i * CELL_SIZE, CELL_SIZE, CELL_SIZE);
                g.setColor(Color.GRAY);
                g.drawRect(j * CELL_SIZE, i * CELL_SIZE, CELL_SIZE, CELL_SIZE);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
