/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio1_s2;

import java.awt.Label;
import java.util.ArrayList;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 *
 * @author Elena Ortega Contreras, subgrupo A2
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    
    TorreDeControl torre;
    
    public void setTorre(TorreDeControl torre){
        this.torre = torre;
    }
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        //setSize(400, 400);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        panelTiempos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel_tiempo = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        panelClasif = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panel_clasif = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 200));

        jButton1.setText("+ 1 vuelta al circuito");
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        panelTiempos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelTiempos.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PANEL DE TIEMPOS");
        panelTiempos.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        panel_tiempo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_tiempo.add(jSeparator1);

        panelTiempos.add(panel_tiempo, java.awt.BorderLayout.CENTER);

        jPanel1.add(panelTiempos);

        panelClasif.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelClasif.setLayout(new java.awt.BorderLayout());

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PANEL CLASIFICACIÓN");
        panelClasif.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        panel_clasif.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_clasif.add(jSeparator2);

        panelClasif.add(panel_clasif, java.awt.BorderLayout.CENTER);

        jPanel1.add(panelClasif);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println("*********************************SIGUIENTE VUELTA*********************************");
        for(CocheFormulaUno c: torre.getCoches()){
            try {
                torre.setTiempo(c);
            } catch (InterruptedException ex) {
                Logger.getLogger(TorreDeControl.class.getName()).log(Level.SEVERE, null, ex);
            }
            }  

        updatePanelTiempo(torre);
        updateClasificacion(torre);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
                
    }
   
    public void updatePanelTiempo(TorreDeControl torre) {
        panel_tiempo.removeAll();
        System.out.println("---------- PANEL TIEMPOS ----------");
        for (CocheFormulaUno c : torre.getCoches()) {            
            String label = "Coche " + c.getNumero() + ", tiempo: " + c.getUltimoTiempo();
            System.out.println("ID: " + c.getId() +" --> Coche " + c.getNumero() + ", tiempo: " + c.getUltimoTiempo());
            JLabel texto = new JLabel(label);
            panel_tiempo.add(texto);
            setVisible(true);
            this.repaint();
            this.revalidate();
        }
    }

    public void updateClasificacion(TorreDeControl torre) {
        panel_clasif.removeAll();
        System.out.println("---------- CLASIFICACIÓN ----------");
        ArrayList<CocheFormulaUno> lista_ordenada = new ArrayList<>(torre.getCoches());
        Collections.sort(lista_ordenada);
        for (CocheFormulaUno c : lista_ordenada) {
            String label = "Coche " + c.getNumero() + ", tiempo: " + c.getUltimoTiempo();
            System.out.println("ID: " + c.getId() +" --> Coche " + c.getNumero() + ", tiempo: " + c.getUltimoTiempo());
            JLabel texto = new JLabel(label);
            panel_clasif.add(texto);
            setVisible(true);
            this.repaint();
            this.revalidate();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel panelClasif;
    private javax.swing.JPanel panelTiempos;
    private javax.swing.JPanel panel_clasif;
    private javax.swing.JPanel panel_tiempo;
    // End of variables declaration//GEN-END:variables

   
}
